spring:
  datasource:
    url:  jdbc:mysql://${DB_URL}:3306/semogong # jdbc:h2:tcp://localhost/~/capstone #
    username: ${DB_NAME} # park #
    password: ${DB_PASSWORD} #
    driver-class-name: com.mysql.cj.jdbc.Driver # org.h2.Driver #

  jpa:
    hibernate:
      ddl-auto : update # update !!!! 꼭 AWS 쓸 때는 update 로 !!!!
    properties:
      hibernate:
        format_sql : true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace # p6spy로 대체
